FROM ros:humble

SHELL ["/bin/bash", "-c"]
WORKDIR /app

# Update
RUN apt-get update -y && apt-get upgrade -y

# Install ROS Packages
RUN apt-get install ros-humble-image-tools -y
RUN apt-get install wget unzip -y
RUN apt-get install can-utils -y

# Configure ROS Environement
ENV ROS_DOMAIN_ID 69

# Copy Files
COPY ./src ./src
COPY ./scripts ./scripts

# Install pip3
RUN apt install python3-pip -y

# Install necessary dependencies with pip
RUN ls src
RUN cd scripts/ && pip3 install -r ./python-can-requirements.txt

# Configure CAN Envirnoment
RUN cd scripts/ && bash ./cyphal_env_config.sh
RUN echo "export PATH=~/.local/bin/:$PATH" >> ~/.bashrc

# Install ROSDep requirements
RUN . /opt/ros/humble/setup.sh && \
	rosdep install -i --from-paths src

# Build Packages
RUN . /opt/ros/humble/setup.sh && \
	colcon build 

# COPY scripts/udev-rules /etc/udev/rules.d/
COPY ./ros_entrypoint.sh /
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]

